### ISSUE TITLE
又一个死项目

### ISSUE THREAD

**Issue by evolutionjay** [AlloyTeam/AlloyTicker#1]
一眼看下去以为是 `GreenSock | GSAP` 的东西
然后打开源码一看....
性能好low，作者麻烦在 Retina 分辨率下看看，肉眼能看到的卡顿。

**Comment by dntzhang** [comment]
和GreenSock | GSAP理念不一样~~  alloyticker希望倒流的可编程性高一些。 性能问题可以把setInterval替换成requestInterval。@evolutionjay
